apiVersion: v1
kind: Service
metadata:
  name: echoserver3b
  namespace: echoserver3
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver3b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver3b
  namespace: echoserver3
spec:
  selector:
    matchLabels:
      app: echoserver3b
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver3b
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/echoserver:2.5
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: echoserver3b
  namespace: echoserver3
spec:
  serviceRef:
    name: echoserver3b
    port: 80
  targetGroupName: echoserver3b
  targetType: ip
